### ISSUE TITLE
Error: undefined is not a function

### ISSUE THREAD

**Issue by KishanIos007** [imgly/pesdk-cordova-demo#1]
i dowload the zip file ..extract it and fire make command as you said.. its give me error.. "Error: undefined is not a function" i also copy the license file into proper folder. whats going wrong ???

```
C:\Users\pcq38\Desktop\pesdk-cordova-demo-master\example>make
cordova plugin add .. --link --nofetch
cordova platform add android
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.photoeditorsdk.cordova.demo
        Name: PESDKDemo
        Activity: MainActivity
        Android target: android-25
Subproject Path: CordovaLib
Android project created with cordova-android@6.2.3
Error: undefined is not a function
make: *** [android] Error 1

C:\Users\pcq38\Desktop\pesdk-cordova-demo-master\example>cordova run android
Error: undefined is not a function
```

**Comment by maltebaumann** [comment]
Hey, please ensure you're using the latest node version!

**Comment by KishanIos007** [comment]
I am using 0.12.7 .

**Comment by maltebaumann** [comment]
That doesn't seem like the latest version (I'm running `v7.2.1`), but you can make sure npm is up to date using `npm install npm@latest -g`.

**Comment by KishanIos007** [comment]
for some reason i cannot update my node version.. which is the minimum supported version ??

**Comment by maltebaumann** [comment]
I can't tell you a specific version, as the error is caused by Cordova itself. Please take a look here: https://cordova.apache.org/news/2017/05/04/cordova-7.html

**Comment by KishanIos007** [comment]
Ohk Thanks :)
