### ISSUE TITLE
Premium support Cordova plugin

### ISSUE THREAD

**Issue by dnmd** [imgly/pesdk-cordova-demo#12]
Thanks for providing this demo and writeup! As the title suggests, I was wondering if there are any plans for the creation of a 'premium' corodva plugin (next to the SDK's)? In the landscape of hybrid app development, a major gap exists when it comes to _performant_, _offline_ photo editing tools / sdk's / plugins with features like _stickers_ / _filters_ etc. (which are nowadays expected by default by users), a gap that imho the PhotoEditor SDK fills in perfectly, seriously!

Although the code provided is sufficient to get you started, it is a starting point. And it often ends there due to insufficient knowledge of either Swift or Java (or both). Offering a plugin next to the SDK's, to config the toolset and set the background color, or taking things even and provide a ['snapchat / insta' ui](https://blog.photoeditorsdk.com/how-to-recreate-snapchats-ui-within-a-single-day-with-the-photoeditor-sdk-for-android-e985b348c52c) would be groundbreaking... and given the size of the community (Cordova / Ionic / ...) it may be worth considering... 

Hope to hear from you! :)

**Comment by bcrigler** [comment]
bump.  Yes please.  Add cordova plugin to official support with React Native / Ionic 4 implementations.

**Comment by svendvd** [comment]
We now have a premium plugin available.

Actually, we don't answer any issues in Github. I would ask you to use the ticket system next time instead: https://imglysdk.atlassian.net/servicedesk/customer/portal/1
