### ISSUE TITLE
Editor won't open the first time on android api 26 and higher

### ISSUE THREAD

**Issue by rebeccamcdougal** [imgly/pesdk-cordova-demo#15]
I have the plugin installed and its working correctly on iOS and on android devices that are api 25 or lower. On android devices api 26 and higher the editor won't open the first time. The permissions for READ_EXTERNAL_STORAGE have been granted but when you open the editor the first time it still tries to ask for permissions. 

START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller cmp=com.google.android.packageinstaller/com.android.packageinstaller.permission.ui.GrantPermissionsActivity (has extras)} from uid 10079

If you open the editor again it will recognize the permissions and open correctly. 

Do I need to change or add something specific to have permissions work the first time with api 26 and higher?

**Comment by maltebaumann** [comment]
Hey @rebeccamcdougal,

Sorry for the late reply. Did you manage to resolve the issue?

Thanks,
Malte

**Comment by rebeccamcdougal** [comment]
No we haven't been able to fix it yet. For now we get around it by calling the plugin twice if its the first time it's been opened on an android device with api over 26 so it will recognize the permissions and open but we'd like to find a way to recognize the permissions correctly the fist time so we don't have to call it twice.
