### ISSUE TITLE
Ionic 3

### ISSUE THREAD

**Issue by DevJuliocesar** [imgly/pesdk-cordova-demo#2]
hello, i don't know, how integrate pesdk in ionic 3, please  help me

`fatal: clone of 'git@github.com:imgly/pesdk-cordova-demo.git' into submodule path 'pesdk-cordova-demo' failed
`

**Comment by maltebaumann** [comment]
Hey, this is a `git` issue. Please make sure you call the `git submodule` commands from the root folder (`PESDKDemo`) and check with `git` docs, if you're adding the submodule correctly. Alternatively you can just download this repository and place it in the `PESDKDemo` folder.
