### ISSUE TITLE
Unable to build android apk

### ISSUE THREAD

**Issue by ganeshphatangare** [imgly/pesdk-cordova-demo#24]
trying to build android apk from ionic but it showing some server certificate error.

   > Could not resolve ly.img.android.pesdk:plugin:6.2.7.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve ly.img.android.pesdk:plugin:6.2.7.
         > Could not get resource 'https://artifactory.9elements.com/artifactory/imgly/ly/img/android/pesdk/plugin/6.2.7/plugin-6.2.7.pom'.
            > Could not GET 'https://artifactory.9elements.com/artifactory/imgly/ly/img/android/pesdk/plugin/6.2.7/plugin-6.2.7.pom'.
               > sun.security.validator.ValidatorException: PKIX path validation failed: **java.security.cert.CertPathValidatorException: timestamp check failed**

can you please check

**Comment by svendvd** [comment]
We don't answer any problems in Github. I would ask you to use the ticket system instead: https://imglysdk.atlassian.net/servicedesk/customer/portal/1
