### ISSUE TITLE
[ios] Build error SyntaxError: Expected "/* Begin ", "/* End ", """, or [A-Za-z0-9_.] but "/" found.

### ISSUE THREAD

**Issue by davidgv88** [imgly/pesdk-cordova-demo#3]
```
cordova create pesdk_demo
cd pesdk_demo
cordova platform add ios
cordova plugin add ../pesdk-cordova-demo/ --link
cordova build ios
```

This shows BUILD SUCCEDED but the second time....

```
cordova build ios
```

SyntaxError: Expected "/* Begin ", "/* End ", "\"", or [A-Za-z0-9_.] but "/" found.

Cordova Version 8.0
Xcode Version 9.2

If I open the file "HelloCordova.xcodeproj" shows:
<img width="425" alt="captura de pantalla 2018-03-21 a las 16 39 45" src="https://user-images.githubusercontent.com/679262/37720040-b976f4a2-2d26-11e8-9389-48dc64fb4d09.png">

If i open the file "HelloCordova.xcworkspace" shows:
<img width="869" alt="captura de pantalla 2018-03-21 a las 16 39 57" src="https://user-images.githubusercontent.com/679262/37720041-b9c820e8-2d26-11e8-85f3-c848946d1197.png">

<img width="657" alt="captura de pantalla 2018-03-21 a las 16 40 35" src="https://user-images.githubusercontent.com/679262/37720042-b9f807e0-2d26-11e8-9d5e-fc69ad81ab6c.png">

**Comment by maltebaumann** [comment]
Hey David,
looks pretty broken, but I managed to run into this issue once as well. Not sure how I fixed it though.

I guess you already tried running `cordova clean`? It might help to just remove the platform using `cordova remove platform ios` and repeating the steps.

Another way may be adding the plugin by actually copying, instead of linking it using:
`cordova plugin add cordova-plugin-pesdk --searchpath=..`

Please let me know if this fixes the issue for you and sorry for the inconvenience! Cordova is really tricky sometimes.

**Comment by davidgv88** [comment]
cordova clean shows error:

```
2018-03-21 16:55:48.287 xcodebuild[6886:74705] Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character / at line 1" UserInfo={NSDebugDescription=Unexpected character / at line 1, kCFPropertyListOldStyleParsingError=Error Domain=NSCocoaErrorDomain Code=3840 "Expected terminating '}' for dictionary at line 27" UserInfo={NSDebugDescription=Expected terminating '}' for dictionary at line 27}}
xcodebuild: error: Unable to read project 'HelloCordova.xcodeproj'.
	Reason: Project /Applications/MAMP/htdocs/pesdk_demo/platforms/ios/HelloCordova.xcodeproj cannot be opened because the project file cannot be parsed.
```

If i add the plugin with searchpath shows the same error.

My version of xcode is 9.2

**Comment by davidgv88** [comment]
I tried many times to remove platform and add again.

But always show the same error.... when I build the project the xcodeproj file is corrupted.

**Comment by davidgv88** [comment]
I release the first line but nothing.

<img width="1022" alt="captura de pantalla 2018-03-21 a las 17 10 55" src="https://user-images.githubusercontent.com/679262/37721878-fb35a894-2d2a-11e8-82c8-93799e5487b8.png">

**Comment by davidgv88** [comment]
Can you reproduce the error? 

If you execute these commands does it works?

```
cordova create pesdk_test
cd pesdk_test
cordova platform add ios
cordova plugin add https://github.com/imgly/pesdk-cordova-demo.git
cordova build ios
cordova build ios
```

**Comment by maltebaumann** [comment]
I'm able to reproduce the issue with the commands you listed and may have found a solution:

There is a `after_build` hook declared in the plugins `config.xml` in line 81 that's responsible for correctly embedding our framework. If I remove line 81 from the config.xml I'm able to build the iOS platform multiple times. The script may not be required anymore, as Cordova officially supports embedded frameworks, but I'm not entirely sure. I'll investigate tomorrow and will update this issue whether everything still works.

**Comment by maltebaumann** [comment]
Hey David,
I verified everything still works when removing the build hook. I'm now able to build iOS as often as I want and the SDK loads just fine, when running the example on devices or in the simulator. Thanks for reporting and I hope you are good to go now!

**Comment by davidgv88** [comment]
Wow! Thank you! It's Works!!

Now I will try with ionic!
