### ISSUE TITLE
Plugin options

### ISSUE THREAD

**Issue by davidgv88** [imgly/pesdk-cordova-demo#6]
Hi.

In the example I see that the only parameter is sourceType.
https://github.com/imgly/pesdk-cordova-demo/blob/master/example/www/js/index.js#L41

Can I configure other options?

The options are those of Cordova's cameraOptions object?
https://github.com/apache/cordova-plugin-camera#cameracameraoptions--object

**Comment by maltebaumann** [comment]
Hey David,

looks like I accidentally left `sourceType` parameter in the lines you mentioned during experimentation. The only parameter actually used within the plugin is `path`. If a path is given, the plugin tries to load the image at the path and directly opens the editor with the image.

There are no ties to the `cordova-plugin-camera`, as the PhotoEditor SDK includes a camera implementation as well. For configuration of the camera and/or editor, please take a look at the corresponding sections in our [docs](https://www.photoeditorsdk.com/documentation) for either iOS or Android. Especially the customization sections. You'll have to make any PESDK specific adjustments within the native plugin code (`PESDKPlugin.java` and `PESDKPlugin.m`), as the options are not exposed to Cordova.

Thanks,
Malte
