### ISSUE TITLE
[iOS] Video option

### ISSUE THREAD

**Issue by davidgv88** [imgly/pesdk-cordova-demo#7]
This video option must be deactivated.

This plugin is only for images? When you select a video the photoeditor can not load the video file or crash.

The video option only appears in iOS

## Step 1
![img_2415 2](https://user-images.githubusercontent.com/679262/38029422-1bbb3f32-3296-11e8-954e-ba53e6188f47.jpg)

**Comment by maltebaumann** [comment]
This is caused by a missing `NSMicrophoneUsageDescription` key in your `Info.plist`. But I just pushed an updated version that disables the video recording mode within the plugin.
