### ISSUE TITLE
[Android] Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.

### ISSUE THREAD

**Issue by davidgv88** [imgly/pesdk-cordova-demo#9]
### Error
Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
More than one file was found with OS independent path 'lib/mips/librsjni.so'

<img width="1107" alt="captura de pantalla 2018-07-03 a las 11 09 32" src="https://user-images.githubusercontent.com/679262/42210597-b42413cc-7eb1-11e8-8fee-92343774065c.png">

### Steps for reproduce
```
cordova create co_pesdk
cd co_pesdk
cordova platform add android@7.1.0
cordova plugin add https://github.com/imgly/pesdk-cordova-demo.git
cordova build android
```

### cordova info command:
```
cordova info
Node version: v6.11.0
Cordova version: 8.0.0
Plugins: cordova-plugin-add-swift-support,cordova-plugin-pesdk,cordova-plugin-whitelist
```

**Comment by davidgv88** [comment]
It has always worked for me but it has stopped working.

**Comment by davidgv88** [comment]
@maltebaumann  some idea? It has always worked!

**Comment by davidgv88** [comment]
Ok Thanks!!

**Comment by maltebaumann** [comment]
Hey again, could you try doing the following steps:

1. Ensure all files specify the same Gradle Build tools version (search throughout the /platforms/android directory, as there are multiple files): 
com.android.tools.build:gradle:3.0.0
2. Clean both build folders:
`co_pesdk/platforms/android/build` and `co_pesdk/platforms/android/app/build`

We managed to get it running once all modules were using the same Gradle version. Please let me know if this works for you as well!

**Comment by davidgv88** [comment]
Hi @maltebaumann 

Sorry. I can't reproduce your steps.

When I search "com.android.tools.build:gradle" in platforms/android directory shows this:

<img width="675" alt="captura de pantalla 2018-07-05 a las 8 50 43" src="https://user-images.githubusercontent.com/679262/42306776-9146a182-8030-11e8-8194-5f3a3ee3e321.png">

3 files with the same gradle version (3.0.1) and 1 File with the version (1.0.0+)

I have replaced the 3 files with 3.0.1 by 3.0.0 and then I deleted the two build folders and appears the same error

I have replaced the 4 files with 3.0.1 and then I deleted the two build folders and appears the same error

I have replaced the 4 files with 3.0.0 and then I deleted the two build folders and appears the same error

Please Could you tell me exactly what files you modified? 

Thank you very much for your help.

**Comment by davidgv88** [comment]
I found a posible solution. https://github.com/davidgv88/pesdk-cordova-demo/commit/c8493c6a2e011918f4d62b02fd5df07e7d532333

**Comment by maltebaumann** [comment]
Hey David, your solution might have pointed us in the right direction, but would probably lead to crashes on runtime, as the RenderScript library is needed by the SDK.

There seems to be a bug in Gradle, that leads to the strange linking behavior. We managed to fix it by adding a `pickFirst` command and removing the plugins `compileSdkVersion` and `buildToolsVersion` specifications from our `.gradle` file. We just tested this with the example contained in this repository and everything works on our end. If you still run into errors, please try cleaning everything:
1. `cordova clean` for Android platform files
2. `rm -rf $HOME/.gradle/caches/` for global Gradle caches
3. From `/platforms/android`: `for dir in ./**/build; do rm -fr "$dir"; done;` for any remaining build folders

Again: Sorry for the inconvenience, but that one was especially hard to track down. Please let us know if this fix works for you!

Best, Malte

**Comment by maltebaumann** [comment]
Closing this as it seems to work now.
